### ISSUE TITLE
Separate ga · ba · da · kya · sha... (58 characters) parts

### ISSUE THREAD

**Issue by anzzstuff** [anzzstuff/kanaquiz#2]
Instead of the last group being a huge 58 character group, the checkbox should say something like "Enable alternative characters", which would, for example, add "ga, gi, gu, ge, go" to the question pool when "ka, ki, ku, ke, ko" is selected.

**Comment by anzzstuff** [comment]
2-part chars should probably be called  a "digraph" as opposite of monograph. Maybe an explanation of the term somewhere would be in place? "Enable digraphs (2-parted characters)" is a possibility but then we would still need a separate toggle for ga, gi, gu and stuff...

**Comment by hensm** [comment]
To expand on this, how about adding them as additional separate groups and then the checkbox greying them out and matching the selection state to the base character group? Seems more flexible.

Mockup:
![disabled](https://user-images.githubusercontent.com/6956633/28401208-507276ec-6d10-11e7-8919-1157cf33515d.png)
![enabled](https://user-images.githubusercontent.com/6956633/28401210-54380404-6d10-11e7-9f4e-131ced59091b.png)

I wouldn't mind working on this. I'd have to familiarise myself with React, though.

**Comment by anzzstuff** [comment]
Well, it would be better than the current way, but the problem is that we lose some usability, especially with mobile, because the list would become very long.

**Comment by hensm** [comment]
Nested checkboxes? So it'd be the same length as now, but you could expand it for the extra options.

**Comment by anzzstuff** [comment]
Done, closed.
