### ISSUE TITLE
Cannot choose stage on mobile devices

### ISSUE THREAD

**Issue by trgpa** [anzzstuff/kanaquiz#6]
The up/down arrows on number input field (stage-choice) don't appear. Tried using backspace but no use, maybe because the size attribute is set to 1.
The only way I could do is to copy a digit (say "3") from another place -> select the default value ("1") in stage-choice field -> paste.

[Tested on Samsung Galaxy J5/Chrome 56.0.2924.87]

**Comment by anzzstuff** [comment]
Thanks for the report, definitely something that needs to be fixed.

**Comment by anzzstuff** [comment]
Fixed.
